# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PJ Murray
email: pj.murray.nz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer | Founded Elto.com (sold to GoDaddy.com) | Passionate about remote + distributed
  teams
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pjmurray.nz" # the base hostname & protocol for your site
sass:
  sass_dir: _sass
  style: compressed
twitter_username: pjmurraynz
github_username:  pjmurray
current_location: Costa Rica
# Build settings
markdown: kramdown
permalink:  /blog/:categories/:title.html
interests:
  - Fixed gear cycling
  - Snowboarding
  - Bodyweight fitness
  - Yoga
  - Reading
  - Running
  - Crossfit
  - Kitesurfing
  - Minimalism
technologies:
- Ruby
- Rails
- Python
- Django
- Javavscript (incl. CoffeeScript + ES6)
- React
- Backbone
- Puppet
- OpenStack
- Hadoop
- Mysql
- MongoDB
- Redis