# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PJ Murray
email: pjmurraynz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer | Founded Elto.com (sold to GoDaddy.com) | Passionate about remote + distributed
  teams
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pjmurray.nz" # the base hostname & protocol for your site
twitter_username: pjmurraynz
github_username:  pjmurray

# Build settings
markdown: kramdown
